### PR TITLE
Run `cargo publish --dry-run` before making PR

### PR DESCRIPTION
**Pull request by NobodyXu**
Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by NobodyXu** [comment]
@passcod Running `npm run build` failed with:

```
> release-pr@2.0.5 build
> tsc

src/main.ts:1:30 - error TS2307: Cannot find module 'fs' or its corresponding type declarations.

1 import {promises as fs} from 'fs';
                               ~~~~

src/main.ts:2:40 - error TS2307: Cannot find module 'path' or its corresponding type declarations.

2 import {join, normalize, resolve} from 'path';
                                         ~~~~~~

src/main.ts:11:8 - error TS2307: Cannot find module '@actions/core' or its corresponding type declarations
.

11 } from '@actions/core';
          ~~~~~~~~~~~~~~~

src/main.ts:12:57 - error TS2307: Cannot find module '@actions/exec' or its corresponding type declaration
s.

12 import {exec as _exec, ExecOptions, getExecOutput} from '@actions/exec';
                                                           ~~~~~~~~~~~~~~~

src/main.ts:13:35 - error TS2307: Cannot find module '@actions/github' or its corresponding type declarations.

13 import {getOctokit, context} from '@actions/github';
                                     ~~~~~~~~~~~~~~~~~

src/main.ts:14:33 - error TS2307: Cannot find module 'ejs' or its corresponding type declarations.

src/main.ts:14:33 - error TS2307: Cannot find module 'ejs' or its corresponding type declarations.

14 import {render as _render} from 'ejs';
                                   ~~~~~

src/main.ts:15:20 - error TS2307: Cannot find module 'semver' or its corresponding type declarations.

15 import semver from 'semver';
                      ~~~~~~~~

src/main.ts:18:23 - error TS2307: Cannot find module '@octokit/core' or its corresponding type declarations.

18 import {Octokit} from '@octokit/core';
                         ~~~~~~~~~~~~~~~

src/main.ts:375:9 - error TS2304: Cannot find name '__dirname'.

375    join(__dirname, 'default-template.ejs'),
            ~~~~~~~~~

src/main.ts:480:18 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for
 node? Try `npm i --save-dev @types/node`.

480  const workdir = process.cwd();
                     ~~~~~~~

src/schema.ts:1:31 - error TS2307: Cannot find module '@actions/core' or its corresponding type declarations.

1 import {debug, getInput} from '@actions/core';
                                ~~~~~~~~~~~~~~~

1 import {debug, getInput} from '@actions/core';
                                ~~~~~~~~~~~~~~~

src/schema.ts:2:36 - error TS2307: Cannot find module 'yup' or its corresponding type declarations.

2 import {object, string, bool} from 'yup';
                                     ~~~~~


Found 12 errors in 2 files.

Errors  Files
    10  src/main.ts:1
     2  src/schema.ts:1
```

**Comment by passcod** [comment]
did you run `npm i` before?

**Comment by NobodyXu** [comment]
> did you run `npm i` before?

No, I ran `npm ci` and it fixed the error.

**Comment by passcod** [comment]
I'd prefer this to be:
1. run in the context of "new" cargo-release only (see near the bottom), as old c-r does this already
2. gated behind a flag

**Comment by NobodyXu** [comment]
> I'd prefer this to be:
> 
>     1. run in the context of "new" cargo-release only (see near the bottom), as old c-r does this already
> 
>     2. gated behind a flag

Thanks, I've updated PR as requested.

**Comment by NobodyXu** [comment]
@passcod Pinging just in case you missed the notification.

**Review by passcod — APPROVED** [review]

**Comment by NobodyXu** [comment]
Can we have a new release please @passcod ?

**Comment by passcod** [comment]
sure, tomorrow when i'm not in bed

**Comment by NobodyXu** [comment]
Thanks, I will probably release cargo-binstall v1.0.0 tomorrow evening or Tuesday afternoon then.

**Comment by passcod** [comment]
Done

**Pull request merged**
